mysql: root:12345678x@X@(localhost:3306)/classicmodels?charset=utf8&parseTime=True&loc=Local
postgres: D:\Work\Postgres\bin
sqlite3: ./sqlite.db
mssql: sqlserver://abc:12345678@localhost?database=BikeStores
oracle: oracle://GOLANG:golang@localhost:1521/orcl?standaloneConnection=0&timezone=UTC
